title: João Gilberto Saraiva
author: João Gilberto Saraiva
description: software engineer | professor | writer
url: https://0jonjo.github.io
baseurl: ""
lang: pt
email: jgilbertons@gmail.com
linkedin: 0jonjo
github: 0jonjo

permalink: /blog/:year/:title/
paginate: 4
paginate_path: /blog/page:num/

theme_config:
  appearance: "light"
  appearance_toggle: true
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_reading_time: true
  show_tags: true
  show_code_copy: true
  show_progress_bar: true
  show_back_to_top: true
  show_post_nav: true
  show_toc: true
  show_footnote_tooltips: true
  show_link_previews: false

markdown: kramdown
highlighter: rouge

sass:
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE
  - docs
  - script
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
